## numpy

https://numpy.org/doc/stable/index.html
- 다차원 데이터 처리를 위한 전처리 라이브러리
- 고성능 수치 계산으로 수치해석, 통계, 과학 관련 데이터 처리에 효율적
- 벡터화: 루프 없이 데이터 처리 수행

### List vs narray
List vs narray 성능 비교: 여러 데이터의 합 구하기


In [12]:
import time
data = [1] * 100000000
total = 0
start_time = time.time()
#for x in data:
 #   total += x 얘가 더 시간이 오래걸림
sum(data)
end_time = time.time()
diff = end_time- start_time
print(f"list sum: {diff}")

list sum: 0.20538115501403809


In [ ]:
# 속도가 배는 빠르다..!

import numpy as np
import time
data = np.ones(100000000)
total = 0
start_time = time.time()
totla = np.sum(data)
end_time = time.time()
diff = end_time - start_time
print(f"np num : {diff}")


np num : 0.012240886688232422


In [ ]:
import time
data = [1] * 100000000
start_time = time.time()
#for i in range(len(data)):
#    data[i] += 1
#data = list(map(lamda x:x+1, data))
data = dat +1
end_time = time.time()
diff = end_time - start_time
print(f"list increment : {diff}")
print(data[0])

TypeError: can only concatenate list (not "int") to list

In [21]:
import time
data = np.ones(100000000)
start_time = time.time()
data = data +1
end_time = time.time()
diff = end_time - start_time
print(f"list increment : {diff}")
print(data[0])

list increment : 0.07188892364501953
2.0


narry는 행렬로 계산해줌
- 모든 요소는 동일한 타입을 담는 다차원 배열
- 한번 정해지면 크기 변경 불가
- ndarray 클래스를 사용하여 생성

In [24]:
# 1차원 배열 
import numpy as np

a1 = np.array([1,2,3])
print(a1)
print(a1.ndim) # 차원
print(a1.shape) # 모양
print(a1.size) # 크기
print(a1.dtype) # 데이터 타입
print("=" * 20)

[1 2 3]
1
(3,)
3
int64


In [ ]:
# 2차원 배열
a2 = np.array([[1.0, 2, 3], [4, 5, 6]])
print(a2)
print(a2.ndim)
print(a2.shape)
print(a2.size)
print(a2.dtype)

# 데이터 타입 우선순위 : 문자열 > 실수 > 정수 > 불린
# 배열에 하나라도 존재하면 데이터 타입이 우선순위에 따라 결정됨. 가장 포괄적인 타입을 선택함.


[[1. 2. 3.]
 [4. 5. 6.]]
2
(2, 3)
6
float64


In [ ]:
# 3차원 배열
a3 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(a3)
print(a3.ndim)
print(a3.shape)
print(a3.size)
print(a3.dtype)

# 단어 유사도를 구분할때 쓰임
# 사용자가 남긴 댓글을 3차원 배열에 넣음. 한 단어의 바로 옆 주소 있는건 서로 비슷한 단어로 구분을 할 수 있음


[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
3
(1, 4, 2)
8
int64


In [ ]:
# 배열 연산
a = np.array([1,2,3])
b = np.array([4,5,6])

print("배열의 합 ", a+b)
print("배열의 차 ", a-b)
print("배열의 곱", a*b)
print("스칼라 합", a+1)


배열의 합  [5 7 9]
배열의 차  [-3 -3 -3]
배열의 곱 [ 4 10 18]
스칼라 합 [2 3 4]


TypeError: can only concatenate list (not "int") to list

In [ ]:
# 배열 연산

a = np.array([1,2,3])

print("합", a.sum())
print("평균", a.mean()) # 나누기가 있어서 출력값이 실수로 나온다.
print("최대값", a.max())
print("최소값", a.min())

합 6
평균 2.0
최대값 3
최소값 1


In [ ]:
a = np.array([1,2,3,4,5])

# 인덱싱
b = a[0] # 1
b = a[2] # 3

# 슬라이싱
d = a[1:4] # [2,3,4]
e = a[:3] # [1,2,3]


In [ ]:
# 2차원 

a = np.array([[1,2,3],[4,5,6]])

# 인덱싱
b = a[0,0] # 1
c = a[1,2] # 6

# 슬라이싱
d = a[0,1:3] # [2,3]
e = a[:1] # 모든 줄에서 인덱스 1번째 요소를 모두 출력 [2,5]
f = a[:,:2] 


### 변형

In [ ]:
a = np.array(
[[1,2], 
[3,4],
[5,6]]
    )
# 배열 형태 변경
print(a.reshape((2,3)))

print(a)
print("========"*20)
# 배열 전치
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [52]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# 배열 병합
print(np.concatenate((a,b), axis=0))

[1 2 3 4 5 6]


In [ ]:
a = np.array([1,2,3,4,5,6])
 # 배열 분리
b,c = np.split(a,[3]) # 
print(b,c)

[1 2 3] [4 5 6]


In [56]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

# 배열 분리
b, c = np.split(a,[1], axis=0) # axis 는 축.
print(b)
print("="*20)
print(c)

[[1 2 3]]
[[4 5 6]
 [7 8 9]]


### 주요 함수

In [ ]:
# 배열 크기 정의 및 초기화
# 0으로 채워진 배열

zeros_arr = np.zeros((3,4))
print(zeros_arr)
print(zeros_arr.ndim)
print(zeros_arr.shape)
print(zeros_arr.size)
print(zeros_arr.dtype)

print("="*20)
# 1로 채워진 배열

ones_arr = np.ones((2,3), dtype = np.int16)
print(ones_arr)
print(ones_arr.ndim)
print(ones_arr.shape)
print(ones_arr.size)
print(ones_arr.dtype)

print("="*20)
# 임의의 값
empty_arr = np.empty((2,3)) # 배열안에 임의의 값이 들어간다. 비어있는 배열이 아니다!
print(empty_arr)
print(empty_arr.ndim)
print(empty_arr.shape)
print(empty_arr.size)
print(empty_ar.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
(3, 4)
12
float64
[[1 1 1]
 [1 1 1]]
2
(2, 3)
6
int16
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]
2
(2, 3)


AttributeError: 'numpy.ndarray' object has no attribute 'sizee'

In [ ]:
# arrange :  범위 내 간격 기준 나열
# 시작, 끝, 간격

a1 = np.arange(10, 30, 5)
print(a1)

a2 = np.arang(0,20.3)
print(a2)

[10 15 20 25]


In [ ]:
# linspace:  범위 내 수만큼 균등하게 나눔
# 시작, 끝, 나눌 수 
a1 = np.linespace(0,2,9)
print(a1)

a2 = np.linspace(1,2,10
print(a2))

AttributeError: module 'numpy' has no attribute 'linespace'

In [ ]:
# 0과 1 사이의 균등 분포에서 난수를 생성하여 배열
arr = np.random.random((3,3))
print(arr)

In [ ]:
# 평균이 0이고 표준편차가 1인 정규분포를 따르는 난수를 생성
arr = np.random.raandn(2,4)
print(arr)

AttributeError: module 'numpy.random' has no attribute 'radn'