# numpy
- https://numpy.org/devdocs/index.html
- 다차원 데이터 처리를 위한 전처리 라이브러리
- 고성능 수치 계산으로 수치해석, 통계, 과학 관련 데이터 처리에 효율적 
- 벡터화: 루프 없이 데이터 처리 수행
---

### 설치
     pip install numpy 
---

### List vs narray

### List vs narray 성능 비교: 여러 데이터의 합 구하기

In [5]:
import time
data = [1] * 100000000
total = 0
start_time = time.time()
# for x in data:
#     total += x
total = sum(data)
end_time = time.time()
diff = end_time - start_time
print(f"list sum: {diff}")

list sum: 0.19013714790344238


In [6]:
import time
import numpy as np
data = np.ones(100000000)
total = 0
start_time = time.time()
total = np.sum(data)
end_time = time.time()
diff = end_time - start_time
print(f"np sum: {diff}")

np sum: 0.011912822723388672


### List vs narray 성능 비교: 여러 데이터 조작하기

In [ ]:
import time
data = [1] * 100000000
start_time = time.time()
for i in range(len(data)):
    data[i] += 1
end_time = time.time()
diff = end_time - start_time
print(f"list increment: {diff}")
print(data[0])

In [ ]:
import time
import numpy as np
data = np.ones(100000000)
start_time = time.time()
data = data + 1
end_time = time.time()
diff = end_time - start_time
print(f"np increment: {diff}")
print(data[0])

### 배열

In [ ]:
# numpy 배열은 동일한 타입의 데이터를 담는 다차원 배열
# ndarray 클래스를 사용하여 생성

import numpy as np

# 1차원 배열
a1 = np.array([1, 2, 3])
print(a1)
print(a1.ndim)      # 차원
print(a1.shape)     # 모양
print(a1.size)      # 크기
print(a1.dtype)     # 데이터타입
print("=" * 20)

[1 2 3]
1
(3,)
3
int64
[[1. 2. 3.]
 [4. 5. 6.]]
2
(2, 3)
6
float64
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
8
int64


In [7]:
# 2차원 배열
a2 = np.array([[1.0, 2, 3], [4, 5, 6]])
print(a2)
print(a2.ndim)
print(a2.shape)
print(a2.size)
print(a2.dtype)
print("=" * 20)

[[1. 2. 3.]
 [4. 5. 6.]]
2
(2, 3)
6
float64


In [8]:
# 3차원 배열
a3 = np.array([[[1, 2],[3, 4]],[[5, 6], [7, 8]]])
print(a3)
print(a3.ndim)
print(a3.shape)
print(a3.size)
print(a3.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
8
int64


In [4]:
# 배열 연산

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("배열의 합", a + b)
print("배열의 차", a - b)
print("배열의 곱", a * b)
print("스칼라 합", a + 1)

배열의 합 [5 7 9]
배열의 차 [-3 -3 -3]
배열의 곱 [ 4 10 18]
스칼라 합 [2 3 4]


In [6]:
# 배열 연산

a = np.array([1, 2, 3])

print("합", a.sum())
print("평균", a.mean())
print("최대값", a.max())
print("최소값", a.min())

합 6
평균 2.0
최대값 3
최소값 1


In [3]:
a = np.array([1, 2, 3, 4, 5])

# 인덱싱
b = a[0]  # 1
c = a[2]  # 3

# 슬라이싱
d = a[1:4]  # [2, 3, 4]
e = a[:3]   # [1, 2, 3]
f = a[3:]   # [4, 5]

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])

# 인덱싱
b = a[0, 0]  # 1
c = a[1, 2]  # 6

# 슬라이싱
d = a[0, 1:3]  # [2, 3]
e = a[:, 1]    # [2, 5]
f = a[:, :2]   # [[1, 2], [4, 5]]

### 변형

In [4]:
a = np.array([[1, 2], [3, 4], [5, 6]])

# 배열의 형태 변경
print(a.reshape((2, 3)))
#
print(a)
# 배열 전치
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 배열 병합
print(np.concatenate((a, b)))

[1 2 3 4 5 6]


In [8]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# 배열 병합
print(np.concatenate((a, b), axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [14]:
a = np.array([1, 2, 3, 4, 5, 6])

# 배열 분리
b, c = np.split(a, [3])
print(b, c)

[1 2 3] [4 5 6]


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 배열 분리
b, c = np.split(a, [1], axis=0)
print(b)
print("=" * 20)
print(c)

[[1 2 3]]
[[4 5 6]
 [7 8 9]]


### 주요 함수

In [ ]:
import numpy as np
# 배열 크기 정의 및 초기화
# 0으로 채워진 배열
zeros_arr = np.zeros((3, 4))
print(zeros_arr)
print(zeros_arr.ndim)
print(zeros_arr.shape)
print(zeros_arr.size)
print(zeros_arr.dtype)
# 1로 채워진 배열
ones_arr = np.ones((2, 3), dtype=np.int16)
print(ones_arr)
print(ones_arr.ndim)
print(ones_arr.shape)
print(ones_arr.size)
print(ones_arr.dtype)

# 임의의 값
empty_arr = np.empty((2, 3))
print(empty_arr)
print(empty_arr.ndim)
print(empty_arr.shape)
print(empty_arr.size)
print(empty_arr.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
(3, 4)
12
float64
hero
0.0
hero
[[1 1 1]
 [1 1 1]]
2
(2, 3)
6
int16
[[1.79769313e+308 1.79769313e+308 2.00000000e+000]
 [2.22044605e-016 2.22507386e-308 4.94065646e-324]]
2
(2, 3)
6
float64


In [ ]:
# arange: 범위 내 간격 기준 나열
# 시작, 끝, 간격

a1 = np.arange(10, 30, 5)
print(a1)

a2 = np.arange(0, 2, 0.3)
print(a2)

In [6]:
# linspace: 범위 내 수만큼 균등하게 나눔
# 시작, 끝, 나눌 수

a1 = np.linspace(0, 2, 9)
print(a1)

a2 = np.linspace(1, 2, 10)
print(a2)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [ ]:
# 0과 1사이의 균등 분포에서 난수를 생성하여 배열
# 3x3인 배열을 생성
arr = np.random.random((3, 3))
print(arr)

In [ ]:
# 평균이 0이고 표준편차가 1인 정규 분포를 따르는 난수를 생성
# 2x4인 배열을 생성
arr = np.random.randn(2, 4)
print(arr)

In [ ]:
# EOD.